export const languageNames: Record<string, string> = {
  ab: "abkhaz",
  ace: "acehnese",
  ach: "acholi",
  aa: "afar",
  af: "afrikaans",
  sq: "albanian",
  aaz: "alur",
  am: "amharic",
  ar: "arabic",
  hy: "armenian",
  as: "assamese",
  av: "avar",
  awa: "awadhi",
  ay: "aymara",
  az: "azerbaijani",
  ban: "balinese",
  bal: "baluchi",
  bm: "bambara",
  bci: "baoulé",
  ba: "bashkir",
  eu: "basque",
  btx: "batak karo",
  bts: "batak simalungun",
  bbc: "batak toba",
  be: "belarusian",
  bem: "bemba",
  bn: "bengali",
  bew: "betawi",
  bho: "bhojpuri",
  bik: "bikol",
  bs: "bosnian",
  br: "breton",
  bg: "bulgarian",
  bua: "buryat",
  yue: "cantonese",
  ca: "catalan",
  ceb: "cebuano",
  ch: "chamorro",
  ce: "chechen",
  ny: "chichewa",
  "zh-cn": "chinese (simplified)",
  "zh-tw": "chinese (traditional)",
  chk: "chuukese",
  cv: "chuvash",
  co: "corsican",
  "crh-cyrl": "crimean tatar (cyrillic)",
  "crh-latn": "crimean tatar (latin)",
  hr: "croatian",
  cs: "czech",
  da: "danish",
  prs: "dari",
  dv: "dhivehi",
  din: "dinka",
  doi: "dogri",
  dov: "dombe",
  nl: "dutch",
  dyu: "dyula",
  dz: "dzongkha",
  en: "english",
  eo: "esperanto",
  et: "estonian",
  ee: "ewe",
  fo: "faroese",
  fj: "fijian",
  fil: "filipino",
  fi: "finnish",
  fon: "fon",
  fr: "french",
  "fr-ca": "french (canada)",
  fy: "frisian",
  fur: "friulian",
  ff: "fulani",
  gaa: "ga",
  gl: "galician",
  ka: "georgian",
  de: "german",
  el: "greek",
  gn: "guarani",
  gu: "gujarati",
  ht: "haitian creole",
  cnh: "hakha chin",
  ha: "hausa",
  haw: "hawaiian",
  he: "hebrew",
  hil: "hiligaynon",
  hi: "hindi",
  hmn: "hmong",
  hu: "hungarian",
  hrx: "hunsrik",
  iba: "iban",
  is: "icelandic",
  ig: "igbo",
  ilo: "ilocano",
  id: "indonesian",
  "iu-latn": "inuktut (latin)",
  iu: "inuktut (syllabics)",
  ga: "irish",
  it: "italian",
  jam: "jamaican patois",
  ja: "japanese",
  jv: "javanese",
  kac: "jingpo",
  kl: "kalaallisut",
  kn: "kannada",
  kr: "kanuri",
  pam: "kapampangan",
  kk: "kazakh",
  kha: "khasi",
  km: "khmer",
  cgg: "kiga",
  kg: "kikongo",
  rw: "kinyarwanda",
  ktu: "kituba",
  trp: "kokborok",
  kv: "komi",
  gom: "konkani",
  ko: "korean",
  kri: "krio",
  ku: "kurdish (kurmanji)",
  ckb: "kurdish (sorani)",
  ky: "kyrgyz",
  lo: "lao",
  ltg: "latgalian",
  la: "latin",
  lv: "latvian",
  lij: "ligurian",
  li: "limburgish",
  ln: "lingala",
  lt: "lithuanian",
  lmo: "lombard",
  lg: "luganda",
  luo: "luo",
  lb: "luxembourgish",
  mk: "macedonian",
  mad: "madurese",
  mai: "maithili",
  mak: "makassar",
  mg: "malagasy",
  ms: "malay",
  "ms-arab": "malay (jawi)",
  ml: "malayalam",
  mt: "maltese",
  mam: "mam",
  gv: "manx",
  mi: "maori",
  mr: "marathi",
  mh: "marshallese",
  mwr: "marwadi",
  mfe: "mauritian creole",
  mhr: "meadow mari",
  mni: "meiteilon (manipuri)",
  min: "minang",
  lus: "mizo",
  mn: "mongolian",
  my: "myanmar (burmese)",
  nhe: "nahuatl (eastern huasteca)",
  ndc: "ndau",
  nr: "ndebele (south)",
  new: "nepalbhasa (newari)",
  ne: "nepali",
  nqo: "nko",
  no: "norwegian",
  nus: "nuer",
  oc: "occitan",
  or: "odia (oriya)",
  om: "oromo",
  os: "ossetian",
  pag: "pangasinan",
  pap: "papiamento",
  ps: "pashto",
  fa: "persian",
  pl: "polish",
  "pt-br": "portuguese (brazil)",
  "pt-pt": "portuguese (portugal)",
  "pa-guru": "punjabi (gurmukhi)",
  "pa-arab": "punjabi (shahmukhi)",
  qu: "quechua",
  kek: "qʼeqchiʼ",
  rom: "romani",
  ro: "romanian",
  rn: "rundi",
  ru: "russian",
  se: "sami (north)",
  sm: "samoan",
  sg: "sango",
  sa: "sanskrit",
  "sat-latn": "santali (latin)",
  sat: "santali (ol chiki)",
  gd: "scots gaelic",
  nso: "sepedi",
  sr: "serbian",
  st: "sesotho",
  crs: "seychellois creole",
  shn: "shan",
  sn: "shona",
  scn: "sicilian",
  szl: "silesian",
  sd: "sindhi",
  si: "sinhala",
  sk: "slovak",
  sl: "slovenian",
  so: "somali",
  es: "spanish",
  su: "sundanese",
  sus: "susu",
  sw: "swahili",
  ss: "swati",
  sv: "swedish",
  ty: "tahitian",
  tg: "tajik",
  zgh: "tamazight",
  "zgh-tfng": "tamazight (tifinagh)",
  ta: "tamil",
  tt: "tatar",
  te: "telugu",
  tet: "tetum",
  th: "thai",
  bo: "tibetan",
  ti: "tigrinya",
  tiv: "tiv",
  tpi: "tok pisin",
  to: "tongan",
  lua: "tshiluba",
  ts: "tsonga",
  tn: "tswana",
  tcy: "tulu",
  tum: "tumbuka",
  tr: "turkish",
  tk: "turkmen",
  tyv: "tuvan",
  ak: "twi",
  udm: "udmurt",
  uk: "ukrainian",
  ur: "urdu",
  ug: "uyghur",
  uz: "uzbek",
  ve: "venda",
  vec: "venetian",
  vi: "vietnamese",
  war: "waray",
  cy: "welsh",
  wo: "wolof",
  xh: "xhosa",
  sah: "yakut",
  yi: "yiddish",
  yo: "yoruba",
  yua: "yucatec maya",
  zap: "zapotec",
  zu: "zulu",
};
